feat: Support dead letter topic.
apache/pulsar-client-python pull request #135
Opened 2023-06-28 15:45 UTC by shibd

### Motivation

#98 Support dead letter topic.

### Modifications
- Add  `ConsumerDeadLetterPolicy `.
- Add dlq_policy param on the `client.subscribe` method.

### Verifying this change
- Add `test_dead_letter_policy` to cover trigger send dlq topic by `redeliver_unacknowledged_messages `, other case covered by cpp client.

### Documentation

- [x] `doc-required` 
(Your PR needs to update docs and you will update later)

- [] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

2023-08-09 03:06 UTC, BewareMyPower commented
Could you resolve the conflicts?

2023-08-15 09:32 UTC, BewareMyPower requested changes

2023-08-15 09:32 UTC, BewareMyPower commented on pulsar/__init__.py
> +                 initial_subscription_name: str = None):
Please add a test for the default constructor. I made the following change:

```diff
diff --git a/tests/pulsar_test.py b/tests/pulsar_test.py
index 70c1f3a..e749c87 100755
--- a/tests/pulsar_test.py
+++ b/tests/pulsar_test.py
@@ -1723,7 +1723,7 @@ class PulsarTest(TestCase):
         dlq_topic = 'dlq-' + topic
         max_redeliver_count = 5
         consumer = client.subscribe(topic, "my-sub", consumer_type=ConsumerType.Shared,
-                                    dead_letter_policy=ConsumerDeadLetterPolicy(dlq_topic, max_redeliver_count, 'init-sub'))
+                                    dead_letter_policy=ConsumerDeadLetterPolicy())
         dlq_consumer = client.subscribe(dlq_topic, "my-sub", consumer_type=ConsumerType.Shared)
 
         # Sen num msgs.
```

and found the test failed.

```
Traceback (most recent call last):
  File "/Users/xuyunze/github.com/bewaremypower/pulsar-client-python/pulsar_test.py", line 1742, in test_dead_letter_policy
    with self.assertRaises(pulsar.Timeout):
AssertionError: Timeout not raised
```

2023-08-15 10:51 UTC, shibd commented on pulsar/__init__.py
> +                 initial_subscription_name: str = None):
I changed `max_redeliver_count` param required, and added a unit test. PTAL.

2023-08-15 11:00 UTC, BewareMyPower approved these changes

2023-08-15 11:16 UTC, merged