[feat] Support consumer batch receive.
apache/pulsar-client-python pull request #33
Opened 2022-11-10 02:30 UTC by shibd

### Motivation

apache/pulsar#9135 

### Modifications
- Support consumer batch receive.

2022-11-10 13:19 UTC, BewareMyPower requested changes
Could you wrap the `BatchReceivePolicy` class into the `pulsar` module? It's better to avoid using the class from `_pulsar` module directly.

2022-11-10 15:27 UTC, shibd commented
> Could you wrap the `BatchReceivePolicy` class into the `pulsar` module? It's better to avoid using the class from `_pulsar` module directly.

Yes, When I coded, I struggled with whether to implement a wrapper. It turns out that implementing a wrapper class can clearly define the input parameters and docs.

I changed it, PTAL.

2022-11-12 03:05 UTC, tisonkun commented
@shibd you may try to rebase on the latest master so that we're sure there's no doc string syntax regression :)

2022-11-15 10:24 UTC, RobertIndie approved these changes

2022-11-16 12:00 UTC, merged